apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tamuhack-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "tamuhack-static-ip"
spec:
  rules:
  - host: tamuhack.org
    http:
      paths:
        - path: /
        - backend:
            serviceName: tamuhack-site-service
            servicePort: 80
  - host: app.tamuhack.org
    http:
      paths:
        - path: /
        - backend:
            serviceName: tamuhack-quill-service
            servicePort: 80
